In [31]:
import numpy as np

In [32]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(list_)
array_list

array([1, 2, 3, 4, 5])

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes,there is difference.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [33]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(list_)
array_list

array([1, 2, 3, 4, 5])

In [34]:
print("Data type of `list_`: ", type(list_))
print("Data type of `array_list`: ", type(array_list))

Data type of `list_`:  <class 'list'>
Data type of `array_list`:  <class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [35]:
## yes there will be change in data types of both the variable

In [36]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(type(num_list))
print(type(num_array))

<class 'list'>
<class 'numpy.ndarray'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [38]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.shape(num_array)

(2, 3)

In [40]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [43]:
array_num = np.zeros((3,3))
array_num

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [48]:
num_array = np.eye(5)
num_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])